name: Artifact policy guard

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  artifact-guard:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Run artifact policy checks
        run: |
          python3 ci/check_repo_artifacts.py \
            --threshold-mb 50 \
            --forbidden-config ci/forbidden-paths.txt
